### ISSUE TITLE
Fixing ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)

### ISSUE THREAD

**Issue by ghost** [evilmartians/chronicles-gql-martian-library#19]
just started following you tutorial (rails and graphql newbie) and got this error on my first query

```
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  
actionpack (6.0.2.2) lib/action_controller/metal/request_forgery_protection.rb:217:in `handle_unverified_request'
actionpack (6.0.2.2) lib/action_controller/metal/request_forgery_protection.rb:249:in `handle_unverified_request'
...
```

The fix was to

```
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

def execute
...
```

(could also have chosen to uncomment the `protect_from_forgery with: :null_session` that was given by the graphql generator but followed the recommendation from https://stackoverflow.com/a/34252150/618099 )

just wanted to share that with you and others trying out the tutorial.

**Comment by DmitryTsepelev** [comment]
Hi @NorfeldtAbtion! In first part of the tutorial we configure our front–end to _send_ a proper CSRF token with each request (in the paragraph starting with `Back to coding. Since we use HTTP POST as a transport, we need to attach a proper CSRF token...`), have you tried it out? Sending CSRF token without disabling verification makes your app more secure 🙂

**Comment by ghost** [comment]
I realized that when I got further down - just wanted to test the queries like described in the tutorial. 
Perhaps it would make sense to have it insecure in the start the tutorial and then teach how to make it secure (as you do later in the tutorial)

It's a great tutorial - I'm learning a lot.

**Comment by DmitryTsepelev** [comment]
Great, I'm happy we've figured it out! Closing the issue for now, don't hesitate to reach out if you have any troubles

**Comment by ghost** [comment]
> Great, I'm happy we've figured it out! Closing the issue for now, don't hesitate to reach out if you have any troubles

@DmitryTsepelev I still have one question related to this topic. I got to the [part 3](https://evilmartians.com/chronicles/graphql-on-rails-3-on-the-way-to-perfection) and can't seem to figure out how to get GraphiQL to show the scheme with the current auth.

How did you get it to show:

![graph schema](https://cdn.evilmartians.com/front/posts/graphql-on-rails-3-on-the-way-to-perfection/me_docs-d7f115c.png)

Guessing that I need to set the headers - but unsure about how to do the CSFR token

<img width="1136" alt="Screenshot 2020-03-27 at 14 16 02" src="https://user-images.githubusercontent.com/53769763/77759728-824ec780-7035-11ea-8e03-d808a48b697d.png">

**Comment by DmitryTsepelev** [comment]
[Looks like](https://github.com/rmosolgo/graphiql-rails/blob/d28581e8eb904e25ebfc961e82273bd8cbd67b9f/lib/graphiql/rails/config.rb#L17) graphiql-rails should set up CSRF token for us, no action should be required. Could you please make sure it's being correctly set up?
